/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as LocaleSplatRouteImport } from './routes/$locale/$'
import { Route as LocaleDonationRouteImport } from './routes/$locale/donation'
import { Route as LocaleFeedRouteImport } from './routes/$locale/feed'
import { Route as LocaleBlogIndexRouteImport } from './routes/$locale/blog/index'
import { Route as LocaleBlogSlugRouteImport } from './routes/$locale/blog/$slug'
import { Route as LocaleEventsIndexRouteImport } from './routes/$locale/events/index'
import { Route as LocaleEventsIdRouteImport } from './routes/$locale/events/$id'
import { Route as LocaleLegalDatenschutzRouteImport } from './routes/$locale/legal/datenschutz'
import { Route as LocaleLegalDatenschutzordnungRouteImport } from './routes/$locale/legal/datenschutzordnung'
import { Route as LocaleLegalImpressumRouteImport } from './routes/$locale/legal/impressum'
import { Route as LocaleLegalSatzungRouteImport } from './routes/$locale/legal/satzung'
import { Route as LocaleProjectsIndexRouteImport } from './routes/$locale/projects/index'
import { Route as LocaleProjectsIdRouteImport } from './routes/$locale/projects/$id'
import { Route as LocaleBlogTagsIndexRouteImport } from './routes/$locale/blog/tags/index'
import { Route as LocaleBlogTagsTagRouteImport } from './routes/$locale/blog/tags/$tag'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleSplatRoute = LocaleSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleDonationRoute = LocaleDonationRouteImport.update({
  id: '/donation',
  path: '/donation',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleFeedRoute = LocaleFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleBlogIndexRoute = LocaleBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleBlogSlugRoute = LocaleBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleEventsIndexRoute = LocaleEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleEventsIdRoute = LocaleEventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleLegalDatenschutzRoute = LocaleLegalDatenschutzRouteImport.update({
  id: '/legal/datenschutz',
  path: '/legal/datenschutz',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleLegalDatenschutzordnungRoute =
  LocaleLegalDatenschutzordnungRouteImport.update({
    id: '/legal/datenschutzordnung',
    path: '/legal/datenschutzordnung',
    getParentRoute: () => LocaleRoute,
  } as any)
const LocaleLegalImpressumRoute = LocaleLegalImpressumRouteImport.update({
  id: '/legal/impressum',
  path: '/legal/impressum',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleLegalSatzungRoute = LocaleLegalSatzungRouteImport.update({
  id: '/legal/satzung',
  path: '/legal/satzung',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleProjectsIndexRoute = LocaleProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleProjectsIdRoute = LocaleProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleBlogTagsIndexRoute = LocaleBlogTagsIndexRouteImport.update({
  id: '/blog/tags/',
  path: '/blog/tags/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleBlogTagsTagRoute = LocaleBlogTagsTagRouteImport.update({
  id: '/blog/tags/$tag',
  path: '/blog/tags/$tag',
  getParentRoute: () => LocaleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/feed': typeof FeedRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$locale/$': typeof LocaleSplatRoute
  '/$locale/donation': typeof LocaleDonationRoute
  '/$locale/feed': typeof LocaleFeedRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/blog/$slug': typeof LocaleBlogSlugRoute
  '/$locale/events/$id': typeof LocaleEventsIdRoute
  '/$locale/legal/datenschutz': typeof LocaleLegalDatenschutzRoute
  '/$locale/legal/datenschutzordnung': typeof LocaleLegalDatenschutzordnungRoute
  '/$locale/legal/impressum': typeof LocaleLegalImpressumRoute
  '/$locale/legal/satzung': typeof LocaleLegalSatzungRoute
  '/$locale/projects/$id': typeof LocaleProjectsIdRoute
  '/$locale/blog/': typeof LocaleBlogIndexRoute
  '/$locale/events/': typeof LocaleEventsIndexRoute
  '/$locale/projects/': typeof LocaleProjectsIndexRoute
  '/$locale/blog/tags/$tag': typeof LocaleBlogTagsTagRoute
  '/$locale/blog/tags/': typeof LocaleBlogTagsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/feed': typeof FeedRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$locale/$': typeof LocaleSplatRoute
  '/$locale/donation': typeof LocaleDonationRoute
  '/$locale/feed': typeof LocaleFeedRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/blog/$slug': typeof LocaleBlogSlugRoute
  '/$locale/events/$id': typeof LocaleEventsIdRoute
  '/$locale/legal/datenschutz': typeof LocaleLegalDatenschutzRoute
  '/$locale/legal/datenschutzordnung': typeof LocaleLegalDatenschutzordnungRoute
  '/$locale/legal/impressum': typeof LocaleLegalImpressumRoute
  '/$locale/legal/satzung': typeof LocaleLegalSatzungRoute
  '/$locale/projects/$id': typeof LocaleProjectsIdRoute
  '/$locale/blog': typeof LocaleBlogIndexRoute
  '/$locale/events': typeof LocaleEventsIndexRoute
  '/$locale/projects': typeof LocaleProjectsIndexRoute
  '/$locale/blog/tags/$tag': typeof LocaleBlogTagsTagRoute
  '/$locale/blog/tags': typeof LocaleBlogTagsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/feed': typeof FeedRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$locale/$': typeof LocaleSplatRoute
  '/$locale/donation': typeof LocaleDonationRoute
  '/$locale/feed': typeof LocaleFeedRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/blog/$slug': typeof LocaleBlogSlugRoute
  '/$locale/events/$id': typeof LocaleEventsIdRoute
  '/$locale/legal/datenschutz': typeof LocaleLegalDatenschutzRoute
  '/$locale/legal/datenschutzordnung': typeof LocaleLegalDatenschutzordnungRoute
  '/$locale/legal/impressum': typeof LocaleLegalImpressumRoute
  '/$locale/legal/satzung': typeof LocaleLegalSatzungRoute
  '/$locale/projects/$id': typeof LocaleProjectsIdRoute
  '/$locale/blog/': typeof LocaleBlogIndexRoute
  '/$locale/events/': typeof LocaleEventsIndexRoute
  '/$locale/projects/': typeof LocaleProjectsIndexRoute
  '/$locale/blog/tags/$tag': typeof LocaleBlogTagsTagRoute
  '/$locale/blog/tags/': typeof LocaleBlogTagsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/$locale'
    | '/feed'
    | '/sitemap.xml'
    | '/$locale/$'
    | '/$locale/donation'
    | '/$locale/feed'
    | '/$locale/'
    | '/$locale/blog/$slug'
    | '/$locale/events/$id'
    | '/$locale/legal/datenschutz'
    | '/$locale/legal/datenschutzordnung'
    | '/$locale/legal/impressum'
    | '/$locale/legal/satzung'
    | '/$locale/projects/$id'
    | '/$locale/blog/'
    | '/$locale/events/'
    | '/$locale/projects/'
    | '/$locale/blog/tags/$tag'
    | '/$locale/blog/tags/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/feed'
    | '/sitemap.xml'
    | '/$locale/$'
    | '/$locale/donation'
    | '/$locale/feed'
    | '/$locale'
    | '/$locale/blog/$slug'
    | '/$locale/events/$id'
    | '/$locale/legal/datenschutz'
    | '/$locale/legal/datenschutzordnung'
    | '/$locale/legal/impressum'
    | '/$locale/legal/satzung'
    | '/$locale/projects/$id'
    | '/$locale/blog'
    | '/$locale/events'
    | '/$locale/projects'
    | '/$locale/blog/tags/$tag'
    | '/$locale/blog/tags'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/$locale'
    | '/feed'
    | '/sitemap.xml'
    | '/$locale/$'
    | '/$locale/donation'
    | '/$locale/feed'
    | '/$locale/'
    | '/$locale/blog/$slug'
    | '/$locale/events/$id'
    | '/$locale/legal/datenschutz'
    | '/$locale/legal/datenschutzordnung'
    | '/$locale/legal/impressum'
    | '/$locale/legal/satzung'
    | '/$locale/projects/$id'
    | '/$locale/blog/'
    | '/$locale/events/'
    | '/$locale/projects/'
    | '/$locale/blog/tags/$tag'
    | '/$locale/blog/tags/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  LocaleRoute: typeof LocaleRouteWithChildren
  FeedRoute: typeof FeedRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/$': {
      id: '/$locale/$'
      path: '/$'
      fullPath: '/$locale/$'
      preLoaderRoute: typeof LocaleSplatRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/donation': {
      id: '/$locale/donation'
      path: '/donation'
      fullPath: '/$locale/donation'
      preLoaderRoute: typeof LocaleDonationRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/feed': {
      id: '/$locale/feed'
      path: '/feed'
      fullPath: '/$locale/feed'
      preLoaderRoute: typeof LocaleFeedRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/blog/': {
      id: '/$locale/blog/'
      path: '/blog'
      fullPath: '/$locale/blog/'
      preLoaderRoute: typeof LocaleBlogIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/blog/$slug': {
      id: '/$locale/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/$locale/blog/$slug'
      preLoaderRoute: typeof LocaleBlogSlugRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/events/': {
      id: '/$locale/events/'
      path: '/events'
      fullPath: '/$locale/events/'
      preLoaderRoute: typeof LocaleEventsIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/events/$id': {
      id: '/$locale/events/$id'
      path: '/events/$id'
      fullPath: '/$locale/events/$id'
      preLoaderRoute: typeof LocaleEventsIdRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/legal/datenschutz': {
      id: '/$locale/legal/datenschutz'
      path: '/legal/datenschutz'
      fullPath: '/$locale/legal/datenschutz'
      preLoaderRoute: typeof LocaleLegalDatenschutzRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/legal/datenschutzordnung': {
      id: '/$locale/legal/datenschutzordnung'
      path: '/legal/datenschutzordnung'
      fullPath: '/$locale/legal/datenschutzordnung'
      preLoaderRoute: typeof LocaleLegalDatenschutzordnungRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/legal/impressum': {
      id: '/$locale/legal/impressum'
      path: '/legal/impressum'
      fullPath: '/$locale/legal/impressum'
      preLoaderRoute: typeof LocaleLegalImpressumRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/legal/satzung': {
      id: '/$locale/legal/satzung'
      path: '/legal/satzung'
      fullPath: '/$locale/legal/satzung'
      preLoaderRoute: typeof LocaleLegalSatzungRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/projects/': {
      id: '/$locale/projects/'
      path: '/projects'
      fullPath: '/$locale/projects/'
      preLoaderRoute: typeof LocaleProjectsIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/projects/$id': {
      id: '/$locale/projects/$id'
      path: '/projects/$id'
      fullPath: '/$locale/projects/$id'
      preLoaderRoute: typeof LocaleProjectsIdRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/blog/tags/': {
      id: '/$locale/blog/tags/'
      path: '/blog/tags'
      fullPath: '/$locale/blog/tags/'
      preLoaderRoute: typeof LocaleBlogTagsIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/blog/tags/$tag': {
      id: '/$locale/blog/tags/$tag'
      path: '/blog/tags/$tag'
      fullPath: '/$locale/blog/tags/$tag'
      preLoaderRoute: typeof LocaleBlogTagsTagRouteImport
      parentRoute: typeof LocaleRoute
    }
  }
}

interface LocaleRouteChildren {
  LocaleSplatRoute: typeof LocaleSplatRoute
  LocaleDonationRoute: typeof LocaleDonationRoute
  LocaleFeedRoute: typeof LocaleFeedRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleBlogSlugRoute: typeof LocaleBlogSlugRoute
  LocaleEventsIdRoute: typeof LocaleEventsIdRoute
  LocaleLegalDatenschutzRoute: typeof LocaleLegalDatenschutzRoute
  LocaleLegalDatenschutzordnungRoute: typeof LocaleLegalDatenschutzordnungRoute
  LocaleLegalImpressumRoute: typeof LocaleLegalImpressumRoute
  LocaleLegalSatzungRoute: typeof LocaleLegalSatzungRoute
  LocaleProjectsIdRoute: typeof LocaleProjectsIdRoute
  LocaleBlogIndexRoute: typeof LocaleBlogIndexRoute
  LocaleEventsIndexRoute: typeof LocaleEventsIndexRoute
  LocaleProjectsIndexRoute: typeof LocaleProjectsIndexRoute
  LocaleBlogTagsTagRoute: typeof LocaleBlogTagsTagRoute
  LocaleBlogTagsIndexRoute: typeof LocaleBlogTagsIndexRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleSplatRoute: LocaleSplatRoute,
  LocaleDonationRoute: LocaleDonationRoute,
  LocaleFeedRoute: LocaleFeedRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleBlogSlugRoute: LocaleBlogSlugRoute,
  LocaleEventsIdRoute: LocaleEventsIdRoute,
  LocaleLegalDatenschutzRoute: LocaleLegalDatenschutzRoute,
  LocaleLegalDatenschutzordnungRoute: LocaleLegalDatenschutzordnungRoute,
  LocaleLegalImpressumRoute: LocaleLegalImpressumRoute,
  LocaleLegalSatzungRoute: LocaleLegalSatzungRoute,
  LocaleProjectsIdRoute: LocaleProjectsIdRoute,
  LocaleBlogIndexRoute: LocaleBlogIndexRoute,
  LocaleEventsIndexRoute: LocaleEventsIndexRoute,
  LocaleProjectsIndexRoute: LocaleProjectsIndexRoute,
  LocaleBlogTagsTagRoute: LocaleBlogTagsTagRoute,
  LocaleBlogTagsIndexRoute: LocaleBlogTagsIndexRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  LocaleRoute: LocaleRouteWithChildren,
  FeedRoute: FeedRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
